inputs:
  name: 
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps: 
    - run: echo Hello ${{ inputs.name }}.
      shell: bash

    - uses: SAP/project-piper-action@master
      with:
        command: version
    - run: echo "Nice to meet you!"
      shell: pwsh
